tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/core"
brew "bash-completion"
brew "git"
brew "nodenv"
brew "python"
brew "rbenv"
brew "telnet"
brew "wget"
brew "wine"
brew "yarn"
cask "1password"
cask "chromium"
cask "dropbox"
cask "firefox"
cask "github"
cask "google-chrome"
cask "iterm2"
# cask "phpstorm"
# cask "sequel-pro"
cask "simplenote"
cask "skitch"
cask "station"
cask "visual-studio-code"

tap "fiahfy/tap"
cask "fiahfy/tap/hosty"
cask "fiahfy/tap/uni"
