#!/bin/sh

DIR=$(cd $(dirname $0); pwd)

ln -sf $DIR/.bash_profile ~/.bash_profile
ln -sf $DIR/.bashrc ~/.bashrc
ln -sf $DIR/.zprofile ~/.zprofile
ln -sf $DIR/.zshrc ~/.zshrc
ln -sf $DIR/.gitconfig ~/.gitconfig
ln -sf $DIR/.gitignore ~/.gitignore
